### ISSUE TITLE
Instructions Page needs to be restyled

### ISSUE THREAD

**Issue by JohanneJayde** [JohanneJayde/EWU-CSCD379-2024-Spring#2]
![intruction page](https://github.com/JohanneJayde/EWU-CSCD379-2024-Spring/assets/114778753/8a60a814-8949-4a6e-9184-6040937a848f)

The instructions page currently is just the Help Dialog moved to an actual page. We need to restyle it to be more interesting. Maybe add in more explanations about pages. Explaining reset, timers buttons.. etc.

**Comment by alyxadarr** [comment]
I have created a second page and added more styling and instructions. Don't know how to pretty it up even more (maybe an animation?) but open to suggestions :)
