### ISSUE TITLE
Logo should change colors as the theme changes

### ISSUE THREAD

**Issue by JohanneJayde** [JohanneJayde/EWU-CSCD379-2024-Spring#5]
https://github.com/JohanneJayde/EWU-CSCD379-2024-Spring/assets/114778753/6738be39-65d0-4102-9c2d-5333fd825a70

Logo is currently the main theme colors only. I think that it would be cool to dynamically change the logo's color themes based on what theme you pick.

**Comment by alyxadarr** [comment]
While I would have loved to figure out how to change the svg file colors dynamically, i just added in all the svg logo files based on themes and changed default.vue to watch the theme and update as it changes .
