### ISSUE TITLE
Handle longer names for player in UI

### ISSUE THREAD

**Issue by JohanneJayde** [JohanneJayde/EWU-CSCD379-2024-Spring#7]
![long name](https://github.com/JohanneJayde/EWU-CSCD379-2024-Spring/assets/114778753/ca362fdf-edb5-46ed-b60c-47e82b289322)

if a user enters in a long name, it will result in it going outside bounds of player name component.

**Comment by alyxadarr** [comment]
Implemented a hover for the full name using v-hover and truncated the string over 8 characters 
<img width="234" alt="Screenshot 2024-05-14 at 6 39 38 PM" src="https://github.com/JohanneJayde/EWU-CSCD379-2024-Spring/assets/96143366/296f9709-2ba8-4bf9-95b1-e1bff04feefe">
